### PR TITLE
Import HackerNews example

### PR DESCRIPTION
**Pull request by IhostVlad**

### CODE REVIEW

**Comment by TatyanaRyzh** [comment]
1. There should be a way to inform customer about **'import'** operation.

2. There's **unexpected logout** after 'submit' page

**Comment by IhostVlad** [comment]
> 4) Sorry, but what's the difference between 'show' and 'ask' pages?
> 5) Login and sign in (create an account) should be in different pages
> 8) There should be a link to account creation https://www.screencast.com/t/0JnFER5niTZG
> 14) "Create AN account", forgot about an article?

Have you seen original Hacker news web site at https://news.ycombinator.com/ ?

**Comment by TatyanaRyzh** [comment]
3. Anyway I guess the blinking our issue that we should fix
4. The original HN has different data in 'show' and 'ask' pages, but we have the same data.
5, 6. If we're a full copy from YCombinator HN - that's okay, we can leave UI details (but I really guess that it's inconvenient).

**Comment by TatyanaRyzh** [comment]
Well done!

Please, make issues for 3 and 6 tasks. Approved.

**Pull request merged**
